namespace Tengio {
    public enum OculusTouchEventTriggerType {
        PointerEnter = 0,
        PointerExit = 1,
        LeftIndexTrigger = 2,
        LeftIndexTriggerDown = 3,
        LeftIndexTriggerUp = 4,
        RightIndexTrigger = 5,
        RightIndexTriggerDown = 6,
        RightIndexTriggerUp = 7,
        LeftHandTrigger = 8,
        LeftHandTriggerDown = 9,
        LeftHandTriggerUp = 10,
        RightHandTrigger = 11,
        RightHandTriggerDown = 12,
        RightHandTriggerUp = 13,
        AButton = 14,
        AButtonDown = 15,
        AButtonUp = 16,
        BButton = 17,
        BButtonDown = 18,
        BButtonUp = 19,
        XButton = 20,
        XButtonDown = 21,
        XButtonUp = 22,
        YButton = 23,
        YButtonDown = 24,
        YButtonUp = 25,
        LeftPointerEnter = 26,
        LeftPointerExit = 27,
        RightPointerEnter = 28,
        RightPointerExit = 29
    }
}
